version: '3.4'

services:
  sov-postgres:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading-data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - sovryn

  trading-data-service:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
        - ./:/app
    working_dir: /app
    environment:
      - APP_NAME=trading-data-service
      - LOG_LEVEL=debug
      - PORT=3000
      - POSTGRES_HOST=sov-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading-data
      - SUBGRAPH_URL=https://subgraph.test.sovryn.app/subgraphs/name/DistributedCollective/sovryn-subgraph
      - IS_TESTNET=true
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - sov-postgres
    networks:
      - sovryn
networks:
  sovryn:
    driver: bridge
    ipam:
      driver: default